server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  server:
    #Abilita o disabilita l'auto preservazione
    enableSelfPreservation: false
    #Durata (in ms) della cache
    responseCacheUpdateIntervalMs: 30000
    #Tempo di attesa in ms di deregistrazione del servizio (def 60000)
    evictionIntervalTimerInMs: 30000
    #Tempo di attesa (in secondi) prima di accettare richieste
    waitTimeInMsWhenSyncEmpty: 5
  client:
    #Un Servizio Eureka è escluso dalla registrazione in Eureka
    registerWithEureka: false
    #Non esegue la cache in locale 
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      
      
#Server Options      
#https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-eureka-server/src/main/java/org/springframework/cloud/netflix/eureka/server/EurekaServerConfigBean.java

#Client Options
#https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/EurekaClientConfigBean.java

#Instance Options
#https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/EurekaInstanceConfigBean.java